# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Technews.lt - \#1 IT naujienos
email: llukas.tyla@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Technews.lt - IT ir technikos naujienos, straipsniai, apžvalgos, kompiuteriai vaizdo plokštės motininės plokštės aušintuvai procesoriai CPU technews news reviews
baseurl: "/static" # the subpath of your site, e.g. /blog
url: "http://technews.lt" # the base hostname & protocol for your site
github_username:  LukasTy

# Build settings
markdown: kramdown
